### ISSUE TITLE
Update to support Gradle 5+

### ISSUE THREAD

**Issue by markjfisher** [GoogleContainerTools/minikube-build-tools-for-java#151]
The current plugin only seems to support Gradle 4.

On Gradle 5, I'm getting the error `java.lang.ClassNotFoundException: org.gradle.api.provider.PropertyState`

Can this plugin be update to support latest versions of gradle?

**Comment by loosebazooka** [comment]
Should be released with 1.0.0-alpha3 in the next day or so.

**Comment by markjfisher** [comment]
Many thanks

**Comment by loosebazooka** [comment]
Sorry, got a little busy, the release is out now: https://plugins.gradle.org/plugin/com.google.cloud.tools.minikube
